---
layout: post
title:  Qual o seu tema?
subtitle:  Uma visão temática dos vereadores
date: "2016-09-05"
published: false
categories: [análise]
tags: [temas]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(screenshot.force = FALSE, echo = FALSE)

library(dplyr, warn.conflicts = F)
library(DT)
library(streamgraph)

anterior = getwd()
setwd(Sys.getenv("VEREADOR_DIR"))
source("vereadores_logic.R")
source("data_access.R")
source("server.R")
setwd(anterior) 

camara_db <- start_camara_db()

library(streamgraph)

contagem = get_sumario_no_tempo(camara_db, "main_theme", apenas_legislacao = TRUE)
```

```{r}
contagem %>%
  filter(ymd(time) <= ymd(20140101), main_theme != "administração") %>%
  streamgraph("main_theme", "count", "time", ) %>%
  sg_fill_brewer("PuOr") %>%
  sg_legend(show = TRUE, label = "gênero: ")

```

**TODO: Criar uma visão temática por vereador, o mote principal é sabermos se o vereador honrou com suas promessas de campanha (não temos como responder se sim ou não, mas os cidadãos podem saber)**
